name: Publish
on:
  push:
    branches: [ master ]
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: ${{ secrets.PROD_SFTP_SERVER }}
        ftp-username: ${{ secrets.PROD_SFTP_USERNAME }}
        ftp-password: ${{ secrets.PROD_SFTP_PASSWORD }}
        git-ftp-args: --insecure
